version: "3.7"
services:
    web-server:
        build:
            dockerfile: php.Dockerfile
            context: .
        restart: on-failure
        volumes:
            - "./html/:/var/www/html/"
        ports:
            - "8080:80"

    mysql-server:
        image: mysql
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./mysql/:/var/lib/mysql
        ports:
            - "9075:3306"

    phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        environment:
            PMA_HOST: mysql-server
            PMA_USER: root
            PMA_PASSWORD: secret
        ports:
            - "5000:80"
        depends_on:
            - mysql-server
        links:
            - mysql-server
